### ISSUE TITLE
High idle CPU usage on Windows

### ISSUE THREAD

**Issue by sopium** [stjepang/smol#111]
Smol is not correctly simulating edge triggering on Windows. Although it uses `EPOLLONESHOT`, it always [`reregister`](https://github.com/stjepang/smol/blob/2071f2a481e64459a99173b384afb33f12c18068/src/reactor.rs#L276)s, so [`wait`](https://github.com/stjepang/smol/blob/2071f2a481e64459a99173b384afb33f12c18068/src/reactor.rs#L262) always returns immediately.

I think this is the underlying issue of https://github.com/async-rs/async-std/issues/773.

**Comment by stjepang** [comment]
Let's see if this solved the problem: https://github.com/async-rs/async-std/issues/773#issuecomment-628814905

**Comment by sopium** [comment]
It's not fully fixed. Run the `tcp-server` and `tcp-client` examples. When a connection is active, the CPU usage is still high.

It's because when a `TcpStream` is writable (EPOLLOUT), `epoll_wait` always returns immediately even when we are only interested in the readable event (EPOLLIN | EPOLLONESHOT). We have to `reregister` **without** `EPOLLOUT` in this case (and vice versa).

**Comment by sopium** [comment]
It seems that `IoEvent` is no longer working on windows. (Try the `ctrl-c` example.) You need to `reregister` after draining the socket [here](https://github.com/stjepang/smol/blob/661c7db6e2fee08acdc6172b6ea1529ffffa537d/src/io_event.rs#L72).

**Comment by stjepang** [comment]
@sopium Thank you! Is the problem fixed now in the latest version?

**Comment by sopium** [comment]
> @sopium Thank you! I did that - is the problem fixed now in the latest version?

I don't think so. `IoEvent` is working. But this problem is not solved:

> It's not fully fixed. Run the `tcp-server` and `tcp-client` examples. When a connection is active, the CPU usage is still high.
> 
> It's because when a `TcpStream` is writable (`EPOLLOUT`), `epoll_wait` always returns immediately even when we are only interested in the readable event (`EPOLLIN` | `EPOLLRDHUP`). We have to `reregister` **without** `EPOLLOUT` in this case (and vice versa).

You cannot always reregister with all flags. When you are waiting for a stream to become readable but the stream is already writable, you want reregister with **only** `EPOLLIN | EPOLLRDHUP | EPOLLONESHOT`, and vice versa.

I think you may need to make some API changes, and track read/write interests separately. E.g. instead of `with` and `with_mut`, make it `read_with`, `write_with`, `read_with_mut`, `write_with_mut`. When you get a `WouldBlock` error from `read_with`/`read_with_mut`, mark the stream not ready for read. Do the same with `write_with`/`write_with_mut`. When you `reregister`, check whether the stream is ready for read or write, and only reregister for the directions that are not ready.

**Comment by sopium** [comment]
I have a hacky, incomplete but somewhat working fix at https://github.com/stjepang/smol/commit/63d61f527cc4a0e824a29dffac95bd8bc66bbaad.

**Comment by stjepang** [comment]
Do you think we could simulate edge-triggering using oneshot-triggering?

**Comment by sopium** [comment]
> Do you think we could simulate edge-triggering using oneshot-triggering?

Yes, but not without assistance from upper layers, I guess.
